### ISSUE TITLE
如何对接llvm？

### ISSUE THREAD

**Issue by fawdlstty** [zy445566/llvm-guide-zh#2]
<https://github.com/llvm/llvm-project/releases>
我在这个页面下载LLVM-12.0.0-win32.exe并安装后，发现头文件很少，toy.cpp
<https://github.com/zy445566/llvm-guide-zh/blob/master/Chapter03/toy.cpp>
这里面用到的头文件安装包里都没有，是否能提供具体安装步骤？

**Comment by ggssh** [comment]
> https://github.com/llvm/llvm-project/releases 我在这个页面下载LLVM-12.0.0-win32.exe并安装后，发现头文件很少，toy.cpp https://github.com/zy445566/llvm-guide-zh/blob/master/Chapter03/toy.cpp 这里面用到的头文件安装包里都没有，是否能提供具体安装步骤？

最好在Linux下进行开发吧，一定要在Windows下开发的话，可以参考官方文档：[Getting Started with the LLVM System using Microsoft Visual Studio](https://llvm.org/docs/GettingStartedVS.html)

**Comment by mingyEx** [comment]
> https://github.com/llvm/llvm-project/releases 我在这个页面下载LLVM-12.0.0-win32.exe并安装后，发现头文件很少，toy.cpp https://github.com/zy445566/llvm-guide-zh/blob/master/Chapter03/toy.cpp 这里面用到的头文件安装包里都没有，是否能提供具体安装步骤？

windows下面安装挺坑的，有一个文件夹的位置在Github上的路径与git clone下来的不在一起，需要手动移动。
好像是[这个](https://github.com/llvm/llvm-project/tree/main/llvm/utils) 和[这里](https://github.com/llvm/llvm-project/tree/main/utils),另外还有[几个](https://cxuesong.com/archives/1056)需要移动位置的文件夹。
此方法build完成之后，万花筒会以子项目的形式给出，可以直接调试修改。
如果使用vcpkg 来安装llvm的话，配置起来会遇到一堆问题，且使用vcpkg安装[需要一定的硬盘空间](https://github.com/microsoft/vcpkg/issues/21552#issuecomment-975461831)来编译,然后遇到找不到头文件啦，链接库需要自己指定啦，头文件的版本号与教程代码就差一点点子版本号而导致运行错误啦之类的问题。
总之就是非常麻烦，还是linux好。
